export const Labels = {
  success: "S",
  failed: "F",
  num_401: 401,
  zero: 0,
  alert:"Alert!",
  noDataFound: "No Data Found",
  pleaseTryAgainSomeTime:"No response from server, please try again after sometime.",
  somethingWentWrong: "Something went wrong",
  source: "FinancePlanet",
  invalidCredentials: "Invalid credentials",
  unAutorizedNoToken: "Unauthorized: No token",
  invalidExpiredToken: "Unauthorized: Invalid or expired token",
  successMsg: "Success",
  failedMsg: "Failed",
  logoutSuccessfully: "Logout successfully",
  call: "CALL",
  fileProcessSuccess: "File processed successfully",
  unableToAccessFile:"File access failed: unable to locate or open the uploaded file",
  fileNotFound:"Uploaded file not found. Please ensure the file is selected and uploaded correctly.",
  filePathNotFound: "File path is invalid or missing.",
  missing: "M",
  missingColumns: "Missing columns in uploaded file",
  extraColumns: "Extra columns in uploaded file",
  inValidColumnMappingDetails: "Invalid column mapping details",
  batchNumber: "batchNumber",
  unSupportedFile: "Unsupported file format",
  noEmailsFoundLastFewDays:"No emails found from this sender in last few days.",
  attachmentZip: "attachment.zip",
  failedToFetchEmail: "Failed to fetch emails",
  notValidZip: "Not a valid ZIP file.",
  rtaConfigNotFound: "RTA config not found",
  flagGet: "G",
  flagEdit: "E",
  flagDelete: "D",
  loginMsg:"Login failed",

  Service: {
    auth:"auth-service.ts",
    common: "common.ts",
  },

  Methods: {
    adLoginService:"adLoginService",
  },

  Remark: {
    uploadStarted: "Upload started",
    uploadFailed: "Uploaded failed",
    uploadSuccess: "Uploaded successfully",
    processStarted: "Process started",
    processFailed: "Process failed",
    processComplete: "Process completed",
    fileRecieved: "File received successfully",
    dataTableConvertFailed: "File can't able to convert into DataTable",
    dataTableConverted: "File converted into DataTable",
    inValidColumnDetails: "Received invalid Column mapping details",
    validColumnDetails: "Received valid Column mapping details",
    exceptionColumns: "ExceptionColumns found in the uploaded file",
    processProcedureNotAvailable: "Process Procedure not available",
    stagingTableNameNotAvailable: "Staging table name not available",
    actualColumnAndTableColumnEqual: "Actual column and Table column equal",
    actualColumnAndTableColumnNotEqual:"Actual column and Table column not equal",
  },

  FileExtensions: {
    excelFormat: [".xlsx", ".xls"],
    csvFormat: [".csv", ".txt"],
    dbfFormat: [".dbf"],
    rtaSupported: [".xlsx", ".xls", ".csv", ".txt", ".dbf"],
    bseSupported: [".xlsx", ".txt"],
  },

  LoginData: {
    key: "bfcvJCbmwS0qaQRmamEyJg==",
  },

  genericDBError: "Database error occurred",
  genericError: "An error occurred",
  loginMsgpleaseTryAgainSomeTime: 'No response from server, please try again after sometime.',
  login: {
    credentialsError: "Please check your credentials",
    emailMobileError: "Kindly provide valid Email or Mobile number",
    emailError: "Kindly provide valid email",
    mobileError: "Kindly provide valid mobile number",
    otpError: "Kindly provide OTP",
    otpExpired: "OTP Expired",
    otpSent: "OTP sent successfully",
    otpResent: "OTP resent successfully",
    otpSendingTitle: "Sending OTP...",
    otpSendingMessage: "",
    otpVerificationTitle: "Verifying OTP",
    otpVerificationMessage: "",
    otpVerified: "OTP verified successfully",
    otpFailed: "OTP verification failed",
    otpNotVerified: "OTP not verified",
    otpNotSent: "OTP not sent",
    otpSentNotification: "OTP has been sent to your ",
    otpValidNotification: "OTP Verified Successfully",
    verificationDBError: "Unable to verify. Something went wrong on our end",
    userNotFound: "User not found",
    passwordorOtpError: "Please enter password or Request OTP",
    validateEmailError: "Email is not registered with us",
    validateMobileError: "Mobile number is not registered with us",
    validationSuccess: "Validation successful",
    MobileNotRegistered: "Mobile number is not registered with us",
    EmailNotRegistered: "Email is not registered with us",
    passwordNotMatch: "Password does not match",
    changePasswordTitle: "Updating Password.. Please wait!",
    changePasswordMessage: "",
    userIDError: "Kindly provide valid userid",
    passwordError: "Kindly provide valid password",
    userIdAndPasswordError: "Kindly provide valid userid and password",
  },
  sms: {
    sendSuccess: "SMS sent successfully",
    smsError: "Failed to send SMS",
    sendError: "Error sending SMS",
    sendFailed: "Failed to send SMS",
    customResponse: "Custom Response",
    validationError: "Invalid mobile number / SMS",
    OtpSaveError: "Saving Otp failed",
    sendingOtp: "Sending OTP... Please wait!",
  },
  email: {
    sendSuccess: "Email sent successfully!",
    emailError: "Failed to send Email",
    sendError: "Error sending Email",
    sendFailed: "Failed to send Email",
    customResponse: "Custom Response",
    validationError: "Invalid Email address",
  },
  progress: {
    defaultTitle: "Just a moment please...",
    defaultContent: "",
    fetchData: "Fetching data... Please wait!",
    veryfyingOtp: "Verifying OTP... Please wait!",
    sendingOTP: "sending OTP... Please wait!",
    dataSaving: "Saving data...Please wait!",
  },
};
